### PR TITLE
added system dependency on README.md

### PR DESCRIPTION
**Pull request by kibablu**

### CODE REVIEW

**Comment by gruz0** [comment]
Hey! I think I need to fix some issues in `.travis-ci.yml` before accepting PR. I'll reply ASAP

**Comment by kibablu** [comment]
> I fixed it.
> Try to rebase from master branch and push it again.
> 
> ```shell
> git pull --rebase origin master
> ```

Done

**Comment by gruz0** [comment]
Show me result of this command, please:

```bash
git remote -v
``

**Comment by gruz0** [comment]
I've added `CONTRIBUTING.md` file and now there is a place to store technical information about project. Please rebase again, update your PR and push changes. Thx!

**Comment by kibablu** [comment]
Am getting errors 
git

**Comment by kibablu** [comment]
When I run `git pull` it is up to date 
I edited _docs/update-readme_ **branch** and opened a new PR

Let me know if I should do something else

Am new to git sorry :( for the trouble and Thank you for letting me contribute to your Repo am Learning a lot

**Pull request closed without merging**
